name: All tests using PHPUnit

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Setup PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: '7.3'

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run all tests
      run: composer run-script test

    - name: Send data to coveralls
      env: # Or as an environment variable
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: composer run-script generate-coveralls